AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  verify jwt token, must deploy to us-east-1

Globals:
  Function:
    Timeout: 5

Resources:
  EdgeAuthExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
        - Effect: Allow
          Principal:
            Service:
            - edgelambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*

  LambdaEdgeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: edge-us-east-1/
      Handler: edge-function-verify-jwt.lambda_handler
      Runtime: python3.8
      MemorySize: 128
      Role:  !GetAtt EdgeAuthExecutionRole.Arn
      AutoPublishAlias: DontCare
# version:
#   Type: AWS::Lambda::Version
#   Properties:
#     FunctionName: !Ref LambdaEdgeFunction
#     Description: v1

Outputs:
  EdgeFunctionArn:
    Description: auth lambda
    Value: !GetAtt LambdaEdgeFunction.Arn
    Export:
      Name: EdgeFunctionArn
  EdgeFunctionName:
    Description: auth lambda
    Value: !Ref LambdaEdgeFunction
    Export:
      Name: EdgeFunctionName

