AWSTemplateFormatVersion: '2010-09-09'
Description: userpool
Parameters:
  PoolName:
    Type: String
    Description: cognito pool name
  CallbackUrl:
    Type: String
    Description: callback url inc index.html

Resources:
  UserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: !Sub ${PoolName}
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
          - Name: verified_phone_number
            Priority: 2
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          Required: true
          Mutable: true

  UserPoolDomain: 
    Type: AWS::Cognito::UserPoolDomain 
    Properties:
      UserPoolId: !Ref UserPool 
      Domain: !Sub "${PoolName}-bernardjasonhere-pool-domain"

  UserPoolTestClient:
    Type: 'AWS::Cognito::UserPoolClient'
    Properties:
      ClientName: GuiSignOn
      GenerateSecret: true
      UserPoolId: !Ref UserPool
      CallbackURLs:
        - !Sub "${CallbackUrl}/index.html"
      LogoutURLs:
        - !Sub "${CallbackUrl}/index.html"
      SupportedIdentityProviders:
        - COGNITO
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows: 
        - implicit
        - code
      AllowedOAuthScopes:
        - openid
        - aws.cognito.signin.user.admin
      # cognito user pool and client credentials.

Outputs:
    UserPoolArn:
        Description: UserPoolArn
        Value: !GetAtt UserPool.Arn
        Export:
           Name: !Sub "${PoolName}-UserPool"
    UserPoolId:
      Description: UserPoolArn
      Value: !Ref UserPool
      Export:
        Name: !Sub "${PoolName}-UserPoolId"
    ClientId:
      Description: ClientId
      Value: !Ref UserPoolTestClient
      Export:
        Name: !Sub "${PoolName}-ClientId"
    UserPoolUrl:
      Description: UserPoolUrl
      Value: !Sub "https://${UserPoolDomain}.auth.us-east-1.amazoncognito.com"
      Export:
        Name: UserPoolUrl

