version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "eu-databasesetup"
s3_prefix = "backend"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
