AWSTemplateFormatVersion: '2010-09-09'
Description: apigw custom domain

Parameters:
  domainName:
    Type: String
    Default: bernard.dev1.2d4a1d743138c0f.euwe2.prd-plat.aws.bt.com
  myCertificate:
    Type: String
    Default: "arn:aws:acm:eu-west-2:006684448952:certificate/a9e5b94f-6862-4793-90c4-f6697ba614aa"
  truststoreUri:
    Type: String
    Default: s3://bernard-mnp-sam-app-mnpreport/truststore.pem
  # you can get this from route53 console, edit your dns entry or from /BT/Services/Dns/PublicHostedZoneId
  hostedZoneId:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/BT/Services/Dns/PublicHostedZoneId'

Resources:
  myDomainName:
    Type: 'AWS::ApiGateway::DomainName'
    Properties:
      DomainName: !Ref domainName
      SecurityPolicy: TLS_1_2
      RegionalCertificateArn: !Ref myCertificate
      EndpointConfiguration:
        Types:
          - REGIONAL
      MutualTlsAuthentication:
        TruststoreUri: !Ref truststoreUri
  Route53RecordSetGroup:
    Type: AWS::Route53::RecordSet
    DependsOn:
      - myDomainName
    Properties:
      Name: !Ref domainName
      Type: A
      HostedZoneId: !Ref hostedZoneId
      AliasTarget:
        DNSName: !GetAtt myDomainName.RegionalDomainName
        EvaluateTargetHealth: true
        HostedZoneId: !GetAtt myDomainName.RegionalHostedZoneId
  myMapping:
    Type: 'AWS::ApiGateway::BasePathMapping'
    Properties:
      DomainName: !Ref myDomainName
      RestApiId: !ImportValue ApiGwRestApiId
      Stage: Dev