version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "eu-bernard-apigw"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Stage=\"Dev\" S3BucketName=\"bernard-apigw\""
